services:
  stock-api-service:
    build: .
    container_name: stock-api-container
    ports:
      - "8085:8080"
    networks:
      - devops-net
    restart: always

networks:
  devops-net:
    external: true # Dışarıda oluşturduğumuz ağı kullanacak